// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CoreAccessControl.DataAccess.Ef.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using CoreAccessControl.DataAccess.Ef.Models;
using CoreAccessControl.DataAccess.Ef.StoreProcs;

namespace CoreAccessControl.DataAccess.Ef.Data
{
    public partial class CoreaccesscontrolContext : DbContext
    {
        public virtual DbSet<Administrator> Administrator { get; set; }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            modelBuilder
            .Entity<Administrator>(eb =>
            {
                eb.HasNoKey();
            });
        }
    }
}