// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class Device
    {
        public Device()
        {
            DeviceSpace = new HashSet<DeviceSpace>();
            KeyholderDevice = new HashSet<KeyholderDevice>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(10)]
        public string SerialNumber { get; set; }
        public long LocationId { get; set; }
        public long? StatusId { get; set; }
        [Column("DeviceName_ID")]
        public int? DeviceNameId { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty("Device")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty(nameof(Devicestatus.Device))]
        public virtual Devicestatus Status { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DeviceSpace> DeviceSpace { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<KeyholderDevice> KeyholderDevice { get; set; }
    }
}