// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class DeviceSpace
    {
        [Key]
        public long Id { get; set; }
        public long SpaceId { get; set; }
        public long DeviceId { get; set; }

        [ForeignKey(nameof(DeviceId))]
        [InverseProperty("DeviceSpace")]
        public virtual Device Device { get; set; }
        [ForeignKey(nameof(SpaceId))]
        [InverseProperty("DeviceSpace")]
        public virtual Space Space { get; set; }
    }
}