// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class KeyholderSpace
    {
        [Key]
        public long Id { get; set; }
        public long KeyHolderId { get; set; }
        public long SpaceId { get; set; }

        [ForeignKey(nameof(KeyHolderId))]
        [InverseProperty("KeyholderSpace")]
        public virtual KeyHolder KeyHolder { get; set; }
        [ForeignKey(nameof(SpaceId))]
        [InverseProperty("KeyholderSpace")]
        public virtual Space Space { get; set; }
    }
}