// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class KeyHolder
    {
        public KeyHolder()
        {
            KeyholderDevice = new HashSet<KeyholderDevice>();
            KeyholderSpace = new HashSet<KeyholderSpace>();
            UserKeyMapping = new HashSet<UserKeyMapping>();
        }

        [Key]
        public long Id { get; set; }
        public long? StatusId { get; set; }
        public long LocationId { get; set; }
        [Required]
        [StringLength(10)]
        public string KeySerialNumber { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        public int? State { get; set; }
        [StringLength(4)]
        public string Pin { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty("KeyHolder")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty(nameof(KeyholderStatus.KeyHolder))]
        public virtual KeyholderStatus Status { get; set; }
        [InverseProperty("KeyHolder")]
        public virtual ICollection<KeyholderDevice> KeyholderDevice { get; set; }
        [InverseProperty("KeyHolder")]
        public virtual ICollection<KeyholderSpace> KeyholderSpace { get; set; }
        public virtual ICollection<UserKeyMapping> UserKeyMapping { get; set; }
    }
}