// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class KeyholderDevice
    {
        [Key]
        public long Id { get; set; }
        public long KeyHolderId { get; set; }
        public long DeviceId { get; set; }
        public long KeyDevicePermissionId { get; set; }
        public int? Type { get; set; }
        public long? SpaceId { get; set; }

        [ForeignKey(nameof(DeviceId))]
        [InverseProperty("KeyholderDevice")]
        public virtual Device Device { get; set; }
        [ForeignKey(nameof(KeyHolderId))]
        [InverseProperty("KeyholderDevice")]
        public virtual KeyHolder KeyHolder { get; set; }
    }
}