// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class Location
    {
        public Location()
        {
            Device = new HashSet<Device>();
            Devicestatus = new HashSet<Devicestatus>();
            KeyHolder = new HashSet<KeyHolder>();
            KeyholderStatus = new HashSet<KeyholderStatus>();
            Space = new HashSet<Space>();
            SpaceStatus = new HashSet<SpaceStatus>();
            UserActivity = new HashSet<UserActivity>();
            UserKeyMapping = new HashSet<UserKeyMapping>();
            UserLocation = new HashSet<UserLocation>();
            UserStatus = new HashSet<UserStatus>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("Location")]
        public virtual ICollection<Device> Device { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<Devicestatus> Devicestatus { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<KeyHolder> KeyHolder { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<KeyholderStatus> KeyholderStatus { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<Space> Space { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<SpaceStatus> SpaceStatus { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<UserActivity> UserActivity { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<UserKeyMapping> UserKeyMapping { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<UserLocation> UserLocation { get; set; }
        [InverseProperty("Location")]
        public virtual ICollection<UserStatus> UserStatus { get; set; }
    }
}