// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class SpaceStatus
    {
        public SpaceStatus()
        {
            Space = new HashSet<Space>();
        }

        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public long? LastUpdatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? LastUpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedOn { get; set; }
        public long LocationId { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty("SpaceStatus")]
        public virtual Location Location { get; set; }
        [InverseProperty("Status")]
        public virtual ICollection<Space> Space { get; set; }
    }
}