// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class UserLocation
    {
        public UserLocation()
        {
            UserPermission = new HashSet<UserPermission>();
        }

        [Key]
        public long Id { get; set; }
        public long UserId { get; set; }
        public long LocationId { get; set; }
        public long CreatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime CreatedOn { get; set; }
        public bool IsToolKitEnabled { get; set; }
        public long? StatusId { get; set; }
        public long? LastUpdatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? LastUpdatedOn { get; set; }
        public int State { get; set; }
        [StringLength(200)]
        public string DisabledReason { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty("UserLocation")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty(nameof(UserStatus.UserLocation))]
        public virtual UserStatus Status { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserLocation")]
        public virtual User User { get; set; }
        [InverseProperty("UserLocation")]
        public virtual ICollection<UserPermission> UserPermission { get; set; }
    }
}