// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class UserPermission
    {
        [Key]
        public long Id { get; set; }
        public long UserLocationId { get; set; }
        public bool? HasAdminRead { get; set; }
        public bool? HasAdminEdit { get; set; }
        public bool? HasKeyholderRead { get; set; }
        public bool? HasKeyholderEdit { get; set; }
        public bool? HasDeviceRead { get; set; }
        public bool? HasDeviceEdit { get; set; }
        public bool? HasSpaceRead { get; set; }
        public bool? HasSpaceEdit { get; set; }
        public bool? HasConfigRead { get; set; }
        public bool? HasConfigEdit { get; set; }
        public long LastUpdatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? LastUpdatedOn { get; set; }

        [ForeignKey(nameof(UserLocationId))]
        [InverseProperty("UserPermission")]
        public virtual UserLocation UserLocation { get; set; }
    }
}