// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class UserKeyMapping
    {
        [Key]
        public long Id { get; set; }
        public long UserId { get; set; }
        public long LocationId { get; set; }
        [Required]
        [StringLength(10)]
        public string KeySerialNumber { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime AppliedOn { get; set; }

        public virtual KeyHolder KeySerialNumberNavigation { get; set; }
        [ForeignKey(nameof(LocationId))]
        [InverseProperty("UserKeyMapping")]
        public virtual Location Location { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserKeyMapping")]
        public virtual User User { get; set; }
    }
}