// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreAccessControl.DataAccess.Ef.Models
{
    public partial class User
    {
        public User()
        {
            ChangeEmailRequest = new HashSet<ChangeEmailRequest>();
            UserKeyMapping = new HashSet<UserKeyMapping>();
            UserLocation = new HashSet<UserLocation>();
        }

        [Key]
        public long Id { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [Required]
        [StringLength(250)]
        public string Email { get; set; }
        [Required]
        [StringLength(256)]
        public string PasswordHash { get; set; }
        [StringLength(200)]
        public string SecurityQuestion { get; set; }
        [StringLength(200)]
        public string SecurityQuestionAnswer { get; set; }
        [StringLength(45)]
        public string VerificationToken { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? VerificationTokenExpiry { get; set; }
        public bool? IsEmailVerified { get; set; }
        public bool? IsTemporaryPassword { get; set; }
        public long? LastUpdatedBy { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? LastUpdatedOn { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<ChangeEmailRequest> ChangeEmailRequest { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserKeyMapping> UserKeyMapping { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserLocation> UserLocation { get; set; }
    }
}